name: Semantic Versioning and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: git.imkumpy.in 
  REPOSITORY: kumpy/mc-manager-api

jobs:
  semantic_version:
    name: Semantic Versioning and Docker Tagging
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js (for semantic-release)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install semantic-release
      - name: Install dependencies
        run: npm install semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github

      # Run semantic-release to determine the version
      - name: Run semantic-release
        env:
          GIT_CREDENTIALS: ${{ secrets.DOCKER_REGISTRY_USERNAME }}:${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: npx semantic-release

      # Set the version output as an environment variable
      - name: Set version variable
        id: version
        run: echo "VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

  docker_build:
    name: Docker Build and Push
    needs: semantic_version
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      # Build and tag the Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPOSITORY }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPOSITORY }}:${{ env.VERSION }}

